### ISSUE TITLE
Orocommerce 5, serialized_data cannot be cast automatically to type jsonb

### ISSUE THREAD

**Issue by hamdallah90** [b2bcodext/cms-form-builder#11]
Hello, 

There is an error when trying to add this package to ORO 5 this is the error message when running platform update

`ERROR: An exception occurred while executing 'ALTER TABLE b2b_code_cms_form_response ALTER serialized_data TYPE JSONB':
SQLSTATE[42804]: Datatype mismatch: 7 ERROR:  column "serialized_data" cannot be cast automatically to type jsonb
HINT:  You might need to specify "USING serialized_data::jsonb".`

**Comment by dnahrebecki** [comment]
Hi @hamdallah90 , which DB are you using? mysql or postgres?

**Comment by hamdallah90** [comment]
@dnahrebecki  postgres

**Comment by dnahrebecki** [comment]
Fixed in https://github.com/b2bcodext/cms-form-builder/tree/2.2.1

**Comment by hamdallah90** [comment]
There is also another table

`> Oro\Bundle\EntitySerializedFieldsBundle\Migration\SerializedDataMigration
    ERROR: An exception occurred while executing 'ALTER TABLE b2b_code_cms_field_response ALTER serialized_data TYPE JSONB':
SQLSTATE[42804]: Datatype mismatch: 7 ERROR:  column "serialized_data" cannot be cast automatically to type jsonb
HINT:  You might need to specify "USING serialized_data::jsonb".`

**Comment by dnahrebecki** [comment]
it was also removed, see https://github.com/b2bcodext/cms-form-builder/commit/4c69c3540c51c5ae45e0ef6c853beb208f244cde#diff-3393d4c3dfc9c844a14da2555735edfb15c8ac8573e5bd139c1bb5e8c876fe8cR78-L84

**Comment by hamdallah90** [comment]
i will try to install the oro again. thank you

**Comment by hamdallah90** [comment]
Worked thanks
