### ISSUE TITLE
I can't save my first form

### ISSUE THREAD

**Issue by JAAFALI** [b2bcodext/cms-form-builder#13]
Error msg in red on the top. Contact us for help .

**Comment by dnahrebecki** [comment]
@JAAFALI please provide steps to reproduce and at least what kind of error message appears. Did you check var/logs? That might be helpful as well

**Comment by JAAFALI** [comment]
Hi, Thank you, 
The error is Table b2b_code_cms_form doesn't exist. I will try to update the database and verify.

**Comment by dnahrebecki** [comment]
Please make sure to run oro:platform:update

**Comment by JAAFALI** [comment]
yes, yes, I used this cmd
composer require b2bcodext/cms-form-builder
php bin/console oro:platform:update --force

**Comment by dnahrebecki** [comment]
@JAAFALI can I close this issue?
