### ISSUE TITLE
'jquery-ui' no longer available as of OroPlatform 4.17 and assets build fails when using the cms-form-builder

### ISSUE THREAD

**Issue by jankulma-turbine** [b2bcodext/cms-form-builder#3]
Hi,

As of Oro Platform 4.1.7, `require('jquery-ui');`, which you use in https://github.com/b2bcodext/cms-form-builder/blob/release/2.0/src/B2bCode/Bundle/CmsFormBundle/Resources/public/js/app/components/sortable-fields-component.js#L11, is no longer available. Needs to be replaced with `require('jquery-ui/widgets/sortable');`.

Not sure if that would be BC so I am not creating PR.

**Comment by dnahrebecki** [comment]
Hi @jankulma-turbine thanks for reporting. Looks like we have a BC break in 4.1.7 and `require('jquery-ui');` is deprecated in favor of a specific widget, in this case` require('jquery-ui/widgets/sortable');`.

I'll fix it shorty and push a new tag.

**Comment by dnahrebecki** [comment]
Released in https://github.com/b2bcodext/cms-form-builder/releases/tag/2.0.2.
Hard requirement for OroCommerce `~4.1.7` added
