### ISSUE TITLE
CMS forms index page shows 'no results' when 'b2b_code_cms_form' table does not exist

### ISSUE THREAD

**Issue by kovalchuk-vyacheslav** [b2bcodext/cms-form-builder#8]
<img width="1680" alt="Снимок экрана 2021-07-08 в 11 45 29" src="https://user-images.githubusercontent.com/36442460/124891819-01290300-dfe2-11eb-9540-2c3df2fd7e19.png">
If for some reason table 'b2b_code_cms_form' was not created during upgrade - CMS forms will still be shown, index page works fine (which is confusing) and the only way to figure our that everything is broken is try to create new CMS form
<img width="1678" alt="Снимок экрана 2021-07-08 в 11 48 02" src="https://user-images.githubusercontent.com/36442460/124892228-5c5af580-dfe2-11eb-8b6d-113d46772f7a.png">
I guess index page should show '500 error' in case if table does not exist.

**Comment by dnahrebecki** [comment]
Hi @kovalchuk-vyacheslav , if the table doesn't exist, it means the upgrade process has not been executed properly. If the extension is installed, the assumption is that all of the migrations must be executed.

**Comment by kovalchuk-vyacheslav** [comment]
Well, looks like assumption is wrong in some cases, and the only way to figure it out is by trying to create new CMS form. I guess at least error notification should be shown on index page, if you don't want to show errors there.

**Comment by kovalchuk-vyacheslav** [comment]
In our concrete case this extension was added in Oro 3.1, then removed during 4.2 upgrade (removed tables, but migration record was left), then we added it using 'composer require', got no errors during installation, no errors during upgrade, no errors on index page, thought that everything is ok, deployed it to production and got error only on step of saving new form to database

**Comment by dnahrebecki** [comment]
In this case the upgrade process was wrong - if you removed the tables you should have removed the migration record as well.
